language: php

php: 
    - 5.3
    - 5.4

before_script:
    - composer install --dev
    - phpenv config-add tests/php_extensions.ini

script: phpunit --verbose --coverage-text

services:
  - redis-server
  - memcached